### PR TITLE
created user index page backend

### PR DESCRIPTION
**Pull request by LindquistErik**
created user index page (backend)

### CODE REVIEW

**Comment by orangewolf** [comment]
@LindquistErik can you clarify this code? it looks like it has.a single code comment in it. Did something not get pushed?

**Comment by LindquistErik** [comment]
@orangewolf If I remember correctly, we committed the backend just to be safe. The commit was really for the frontend to have our user index page reviewed. we were going to revisit this commented out line after review...but I had to leave a little early yesterday to pick up my daughter because my wife is sick.

**Comment by Dkellam9** [comment]
Gonna be deleting this one as well, unnecessary.

**Comment by bwanicur** [comment]
If you need to delete this PR, please do it now so we don't have more confusion.

@Dkellam9 @LindquistErik

**Pull request closed without merging**
