### PR TITLE
[WIP] user CRUD controller methods, updated seed file

### PR DESCRIPTION
**Pull request by elemee3**

### CODE REVIEW

**Comment by Dkellam9** [comment]
Probably don't merge this, the real stuff is in a different branch, lotta repeated stuff.

**Review by bwanicur — COMMENTED** [review]
Approved

**Comment by bwanicur** [comment]
Oh - this is the WIP.   Nvm the approved then.

**Comment by orangewolf** [comment]
@elemee3 is this still wip? seems like you may want to wrap this so it doesn't get stale

**Comment by elemee3** [comment]
We'll check in with Dakota on this bit, I'm not sure what exactly happened with this branch or which other branch has the repeated code, we will get this one wrapped up today for sure

**Comment by Dkellam9** [comment]
So yeah, this is a trash branch. I ended up rewriting this code to fix the hard reload problem.


Edit: Totally unrelated, but how would one go about deleting a pull request?

**Comment by bwanicur** [comment]
I think the person that created it can delete it.  @Dkellam9 @elemee3

**Pull request closed without merging**
